name: Update GitHub Stats Gist
on:
    workflow_dispatch:
    schedule:
        - cron: '0 */12 * * *'
    push:
        branches: main
jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
            - run: npm ci
            - run: node index.js
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
                  GIST_ID: 3e8eac4896a510123551adae69606933 # The ID portion from your gist url
                  ALL_COMMITS: true # If `true` it will count all commits, if `false` it will count your last year commits
                  K_FORMAT: false # If `true`, large numbers will be formatted with a "k", for example "1.5k"
